version: '3.8'

services:
  localstack:
    image: localstack/localstack:3.3
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "awslocal", "sns", "list-topics"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 20s
